### ISSUE TITLE
Dose this repo still being updated???

### ISSUE THREAD

**Issue by ErrorBot1122** [ReplayMod/ReplayStudio#14]
Is it?????

and does it still work?????????

**Comment by Johni0702** [comment]
Idk what you're asking. There are commits for MC 1.17.1 from just last month, so yes, it obviously is.
And yes, it does work, it's used extensively in the ReplayMod itself (well, the parts that are used by RM definitely still work, idk about stuff that's not used).

**Comment by ErrorBot1122** [comment]
okay, just wanted to know!
