### ISSUE TITLE
How do you use this if there is no wiki?

### ISSUE THREAD

**Issue by ErrorBot1122** [ReplayMod/ReplayStudio#15]
As I found out, this repo's wiki was never [written](https://github.com/ReplayMod/ReplayStudio/issues/5#issuecomment-398792723) so I don't know how to use this!! Are there any docs anywhere I could use, and is there an app or mod to easily use this "API"?? (I think it is an API, idk)

**Comment by ErrorBot1122** [comment]
there is a better question [here](https://github.com/ReplayMod/ReplayMod/issues/592)

**Comment by ErrorBot1122** [comment]
Actually, this question is more prominent here the in replay mod.

**Comment by Johni0702** [comment]
You don't. If you can't figure out how to use something without a wiki, then you probably shouldn't be using it.

> is there an app or mod to easily use this "API"??

As I said in the other issue, this library is used primarily by the ReplayMod and the ReplayMod exposes all maintained parts of this library somewhere in its user interface.
